#!/usr/bin/env python3
import importlib.util,pathlib,json,time
spec=importlib.util.spec_from_file_location('acceptance',pathlib.Path(__file__).with_name('qa-acceptance.py'))
q=importlib.util.module_from_spec(spec);spec.loader.exec_module(q)
def check(name,fn,t=15):return q.expect(name,fn,t)
q.launch('cloud:filters');check('account filter fixture ready',lambda s:s.get('visibleids')==[101,104])
q.mark();q.keys('Right');check('account second title focus recorded',lambda s:s.get('railfocus')==[0,1])
q.mark();q.keys('Info');check('account options reachable',lambda s:s.get('page')=='cloud-watch-options')
q.mark();q.keys('Down','Down','Select');check('account title sorting selected',lambda s:'Sort this page: title' in s.get('items',[]))
q.mark();q.keys('Back');check('sort retains selected account title by identity',lambda s:s.get('visibleids')==[104,101] and s.get('railfocus')==[0,0])
q.mark();q.keys('Info','Down','Select','Select');check('series-only account filter selected',lambda s:'Show: series' in s.get('items',[]))
q.mark();q.keys('Back');check('empty filtered account page is safely focusable',lambda s:s.get('page')=='cloud-watchlist' and s.get('visibleids')==[] and s.get('scenefocus'))
q.mark();q.keys('Play');check('hidden account card cannot be played',lambda s:s.get('page')=='cloud-watchlist' and s.get('player')!='playing')
q.mark();q.keys('Fwd');check('empty account filter still allows native FF paging',lambda s:s.get('cloudpage')==2 and s.get('visibleids')==[201])
q.command('scripts/device.py','screenshot','build/v16-account-page.jpg')
q.mark();q.keys('Info','Down','Down','Down','Select');check('account options return to unchanged TV-only list',lambda s:s.get('page')=='watchlist' and s.get('watchcount')==1)
q.launch('cloud:logoutwrite');check('logout fixture ready',lambda s:s.get('visibleids')==[101,104])
q.mark();q.keys('Select');s=check('logout fixture membership known',lambda s:s.get('page')=='title' and s.get('cloudknown'))
q.keys(*(['Down']*s['titleactions'].index('cloud-watch')),'Select')
check('slow account mutation pending',lambda s:s.get('cloudpending'))
q.mark();q.keys('Back','Left','Down','Down','Down','Select');check('can navigate to Account during write',lambda s:s.get('page')=='account')
q.mark();q.keys('Select');check('sign-out clears account membership and pending transaction',lambda s:not s.get('signedin') and not s.get('cloudknown') and not s.get('cloudpending') and s.get('watchcount')==1)
time.sleep(7);q.mark();check('late prior-session ACK cannot restore account data',lambda s:s.get('page')=='account' and not s.get('signedin') and not s.get('cloudknown'))
(q.ROOT/'build/qa-cloud-boundary-results.json').write_text(json.dumps(q.results,indent=2))
print('ACCOUNT BOUNDARIES PASS',len(q.results),flush=True)
