#!/usr/bin/env python3
"""Additional decoder/track/persistence checks; run after qa-acceptance.py."""
import importlib.util,pathlib
spec=importlib.util.spec_from_file_location('acceptance',pathlib.Path(__file__).with_name('qa-acceptance.py'));q=importlib.util.module_from_spec(spec);spec.loader.exec_module(q)
q.launch('search:mixed');q.expect('search has initial results before page failure',lambda s:s.get('results')==1)
q.mark();q.keys('Info','Select');q.expect('failed page clears stale prior results',lambda s:"couldn't" in s.get('status','') and s.get('results')==0)
q.launch('stream:104');q.expect('caption fixture reaches playback',lambda s:s.get('player')=='playing',12)
q.keys('Play','Right','Right','Right','Select','Down','Down','Select','Play')
q.expect('English caption uses Unicode sidecar renderer',lambda s:s.get('customcaption') and s.get('captiontext') and not s.get('tracks'),12)
q.mark();q.keys('Play','Select','Down','Down','Down','Select','Play')
q.expect('Persian caption uses shaped RTL renderer',lambda s:s.get('customcaption') and s.get('captiontext') and not s.get('tracks'),12)
q.command('scripts/device.py','screenshot','build/qa-persian.jpg')
q.launch('stream:104');q.expect('subtitle language persists across relaunch',lambda s:s.get('customcaption') and s.get('captiontext') and s.get('player')=='playing',12)
q.mark();q.keys('Play','Right','Right','Right','Select','Down','Select')
q.expect('Off disables native captions',lambda s:s.get('currentcaption')=='Off' and not s.get('customcaption') and not s.get('tracks'))
q.mark();q.keys('Back','Left');q.expect('seek near zero is bounded',lambda s:s.get('position',-1)>=0 and s.get('position',99)<3)
q.mark();q.keys('Fwd','Select');q.expect('remote FF seeks 30 seconds',lambda s:s.get('position',0)>=28 and s.get('player')=='paused')
q.mark();q.keys('Rev','Select');q.expect('remote rewind seeks back',lambda s:0<=s.get('position',99)<4 and s.get('player')=='paused')
q.launch('stream:201');q.expect('series ready for explicit Next',lambda s:s.get('page')=='seasons')
q.keys('Select','Select','Select');q.expect('first episode playing for Next',lambda s:s.get('episode')==11 and s.get('player')=='playing',12)
q.mark();q.keys('Select','Right','Right','Right','Right','Right','Right','Select')
q.expect('Next button starts next episode with fresh stream',lambda s:s.get('episode')==12 and s.get('player')=='playing',12)
q.expect('season finale advances to next season',lambda s:s.get('page')=='title' and any(x.get('episodeid')==21 and not x.get('completed') for x in s.get('history',[])),20)
print('EXTENDED DEVICE PASS',len(q.results),flush=True)
