#!/usr/bin/env python3
"""Native search/reliability/remote matrix. Synthetic account and local media only."""
import importlib.util,pathlib,time,json
spec=importlib.util.spec_from_file_location('acceptance',pathlib.Path(__file__).with_name('qa-acceptance.py'))
q=importlib.util.module_from_spec(spec);spec.loader.exec_module(q)

def ready(name='search ready'):
    return q.expect(name,lambda s:s.get('searchstate')=='ready' and s.get('page')=='search',18)

q.launch('verify-unauthorized');q.expect('failed fresh verification preserves working login',lambda s:s.get('signedin') and any('failed' in x for x in s.get('message',[])))
q.launch('search-blank');q.expect('blank input remains editable',lambda s:any('Enter a title' in x for x in s.get('message',[])))
q.mark();q.keys('Back');q.expect('blank search can be cancelled',lambda s:s.get('page')=='home' and 'message' not in s)
q.launch('search:focus');ready('multiple results load')
q.mark();q.keys('Right','Right');q.expect('remote focuses third result',lambda s:s.get('railfocus')==[0,2])
q.mark();q.keys('Select');q.expect('focused result opens details',lambda s:s.get('page')=='title')
q.mark();q.keys('Back');q.expect('Back restores exact result focus',lambda s:s.get('page')=='search' and s.get('railfocus')==[0,2])
q.mark();q.keys('Back');q.expect('Back edits existing query',lambda s:'message' in s)
q.mark();q.keys('Back');q.expect('cancel edit preserves results and focus',lambda s:s.get('page')=='search' and 'message' not in s and s.get('railfocus')==[0,2])
q.mark();q.keys('Info','Back');q.expect('options Back preserves result focus',lambda s:s.get('page')=='search' and s.get('railfocus')==[0,2])
q.mark();q.keys('Fwd');q.expect('remote FF loads next page',lambda s:s.get('searchpage')==2 and s.get('searchstate')=='ready')
q.mark();q.keys('Rev');q.expect('remote rewind restores cached page and focus',lambda s:s.get('searchpage')==1 and s.get('searchstate')=='ready' and s.get('railfocus')==[0,2])

q.launch('search:mixed');ready('page-failure fixture loads first page')
q.mark();q.keys('Fwd');q.expect('failed next page presents recovery actions',lambda s:s.get('searchstate')=='error' and 'Back to previous results' in s.get('items',[]),18)
q.mark();q.keys('Down','Select');q.expect('failed page returns to previous results',lambda s:s.get('searchpage')==1 and s.get('searchstate')=='ready')
q.launch('search:empty');q.expect('empty results are not network failure',lambda s:s.get('searchstate')=='ready' and s.get('results')==0)
q.mark();q.keys('Back');q.expect('empty result allows immediate edit',lambda s:'message' in s)
for value in ['all-invalid','wrong-type','malformed']:
    q.launch('search:'+value);q.expect(value+' is recoverable error, not empty',lambda s:s.get('searchstate')=='error')
q.launch('search-race');q.expect('latest rapid query wins',lambda s:s.get('searchquery')=='fresh' and s.get('searchstate')=='ready')
time.sleep(4);q.mark();q.expect('late old query never replaces fresh results',lambda s:s.get('searchquery')=='fresh' and s.get('searchstate')=='ready')
q.launch('search-recovery');ready('transient provider error recovers automatically')
q.launch("search:Schindler's List");q.expect('apostrophe query uses bounded fallback',lambda s:s.get('searcheffectivequery')=='Schindler s List' and s.get('searchstate')=='ready')
q.launch('search:  علي كيان ۲۰۲۶  ');q.expect('Persian query normalized on native device',lambda s:s.get('searchquery')=='علی کیان 2026' and s.get('searchstate')=='ready')
q.command('scripts/device.py','screenshot','build/experience-persian-query.jpg')
q.launch('search:unicode');ready('Persian result fixture renders')
q.command('scripts/device.py','screenshot','build/experience-persian-result.jpg')
q.launch('search:last');ready('bounded-page fixture loads')
q.mark();q.keys('Fwd','Fwd','Fwd');q.expect('rapid FF clamps to final page',lambda s:s.get('searchpage')==2 and s.get('searchstate')=='ready')
q.mark();q.keys('Rev','Rev','Rev');q.expect('rapid rewind clamps to first page',lambda s:s.get('searchpage')==1 and s.get('searchstate')=='ready')

q.launch('stream:201');q.expect('season navigation fixture ready',lambda s:s.get('page')=='seasons')
q.keys('Down','Select');q.expect('second season opens',lambda s:s.get('page')=='episodes')
q.keys('Down','Select');q.expect('second episode opens',lambda s:s.get('page')=='title' and s.get('episode')==22)
q.mark();q.keys('Back');q.expect('Back restores episode selection',lambda s:s.get('page')=='episodes' and s.get('listfocus')==1)
q.mark();q.keys('Back');q.expect('Back restores season selection',lambda s:s.get('page')=='seasons' and s.get('listfocus')==1)
q.launch('search:pages');ready('one-button playback fixture ready')
q.mark();q.keys('Play');q.expect('Play on result starts without detail click',lambda s:s.get('player')=='playing' and s.get('page')=='player',18)
q.launch('stream:111');q.expect('seek fixture playing',lambda s:s.get('player')=='playing',15)
q.mark();q.keys('Play');q.expect('pause before rapid seek',lambda s:s.get('player')=='paused')
q.mark();q.keys('Fwd','Fwd','Select');q.expect('rapid seek accumulates and clamps',lambda s:s.get('seektarget')==59 and s.get('player')=='paused',15)
q.mark();q.keys('Rev','Select');q.expect('seek backwards preserves pause',lambda s:27<=s.get('seektarget',-1)<=30 and s.get('player')=='paused',15)
q.mark();q.keys('Down');q.expect('Down opens subtitles directly',lambda s:s.get('tracks') and s.get('trackkind')=='subtitles')
q.mark();q.keys('Back');q.expect('Back closes picker before playback',lambda s:not s.get('tracks') and s.get('page')=='player')
q.mark();q.keys('Play');q.expect('Play resumes after paused seeking',lambda s:s.get('player')=='playing',15)
q.launch('stream:109');q.expect('stalled source refreshes once and recovers',lambda s:s.get('player')=='playing' and s.get('refreshattempts')==1,35)
q.launch('stream:102');q.expect('permanent failure stops after bounded recovery',lambda s:s.get('page')=='title' and s.get('refreshattempts')==1 and 'failed' in s.get('status','').lower(),30)
q.launch('stream:104');q.expect('subtitles indexed without blocking picture',lambda s:s.get('player')=='playing' and s.get('cacheready'),20)
(q.ROOT/'build/qa-experience-results.json').write_text(json.dumps(q.results,indent=2))
print('EXPERIENCE ACCEPTANCE PASS',len(q.results),flush=True)
