#!/usr/bin/env python3
"""Provider-marker behavior on the native player; synthetic isolated registry."""
import importlib.util,pathlib,json,time
spec=importlib.util.spec_from_file_location('acceptance',pathlib.Path(__file__).with_name('qa-acceptance.py'))
q=importlib.util.module_from_spec(spec);spec.loader.exec_module(q)
def check(name,fn,timeout=15):return q.expect(name,fn,timeout)
def action(name):
 s=q.states()[-1]; target=s['controlactions'].index(name);current=s['control'];q.mark()
 if current!=target:q.keys(*(['Right']*((target-current)%len(s['controlactions']))))
 check('toolbar focuses '+name,lambda s:s.get('controlactions',[None])[s.get('control',0)]==name)
 q.mark();q.keys('Select')
q.launch('stream:119')
check('native playback starts before intro',lambda s:s.get('player')=='playing' and s.get('position',99)<5 and not s.get('introprompt'))
check('prompt appears at provider start',lambda s:s.get('introprompt') and s.get('introtarget')==25)
q.mark();q.keys('Down');check('subtitle picker suppresses intro prompt',lambda s:s.get('tracks') and not s.get('introprompt'))
q.mark();q.keys('Back','Play');check('pause exposes manual intro action',lambda s:s.get('player')=='paused' and 'intro' in s.get('controlactions',[]))
action('intro');check('intro seek preserves pause and exact requested endpoint',lambda s:s.get('player')=='paused' and s.get('seektarget')==25 and not s.get('seeksettling'),20)
check('prompt absent after intro skip',lambda s:not s.get('introprompt') and 'intro' not in s.get('controlactions',[]))
q.mark();q.keys('InstantReplay');check('deliberate replay inside intro restores skip action',lambda s:s.get('player')=='paused' and 'intro' in s.get('controlactions',[]) and not s.get('seeksettling'),20)
q.mark();q.keys('Back');check('paused hidden-controls prompt is visible',lambda s:s.get('player')=='paused' and s.get('introprompt'))
q.mark();q.keys('Select','Select');check('repeated OK does not skip twice',lambda s:s.get('seektarget')==25 and s.get('player')=='paused' and not s.get('seeksettling'),20)
q.launch('stream:122');check('zero-start intro works',lambda s:s.get('introprompt') and s.get('introtarget')==20)
q.mark();q.keys('Select');check('one-button skip continues playing',lambda s:s.get('player')=='playing' and s.get('position',0)>=18 and not s.get('seeksettling'),20)
q.launch('stream:120');check('reversed marker has no skip',lambda s:s.get('player')=='playing' and s.get('introtarget')==-1 and not s.get('introprompt'))
q.launch('stream:121');check('marker beyond real duration has no skip',lambda s:s.get('player')=='playing' and s.get('introtarget')==-1 and not s.get('introprompt'))
q.launch('stream:202');check('series seasons loaded',lambda s:s.get('page')=='seasons')
q.mark();q.keys('Select','Select','Select');check('first episode has intro marker',lambda s:s.get('player')=='playing' and s.get('introprompt') and s.get('episode')==21)
q.mark();q.keys('Up');check('episode controls visible',lambda s:s.get('controls'))
action('next');check('next episode without marker cannot inherit old intro',lambda s:s.get('player')=='playing' and s.get('episode')==22 and not s.get('introprompt') and s.get('introtarget')==-1)
q.launch('stream:119');check('focus boundary fixture playing',lambda s:s.get('introprompt'))
q.mark();q.keys('Up');check('boundary toolbar ready',lambda s:s.get('controls') and 'intro' in s.get('controlactions',[]))
s=q.states()[-1];q.keys(*(['Right']*s['controlactions'].index('close')))
check('close focused before marker expiry',lambda s:s.get('controlactions',[None])[s.get('control',0)]=='close')
# Hold controls on screen with Up; do not activate or seek.
for _ in range(5):q.keys('Up');time.sleep(4)
q.mark();q.keys('Up');check('intro expiry preserves selected action identity',lambda s:s.get('position',0)>=25 and 'intro' not in s.get('controlactions',[]) and s.get('controlactions',[None])[s.get('control',0)]=='close')
q.keys('Back','Back')
(q.ROOT/'build/qa-intro-results.json').write_text(json.dumps(q.results,indent=2))
print('INTRO NATIVE PASS',len(q.results),flush=True)
