#!/usr/bin/env python3
"""Native sleep/seek boundary cases for final v1.4 artifact."""
import importlib.util,pathlib,json,time
spec=importlib.util.spec_from_file_location('acceptance',pathlib.Path(__file__).with_name('qa-acceptance.py'))
q=importlib.util.module_from_spec(spec);spec.loader.exec_module(q)
def check(name,predicate,timeout=15):return q.expect(name,predicate,timeout)
q.launch('v14-remote');check('saved intervals load for real playback',lambda s:s.get('player')=='playing' and s.get('remotestep')==15 and s.get('remoteskip')==60 and s.get('remotereplay')==15)
q.mark();q.keys('Play');check('custom interval test paused',lambda s:s.get('player')=='paused')
q.mark();q.keys('Fwd');check('configured sixty-second skip clamps while paused',lambda s:s.get('player')=='paused' and s.get('seektarget')==59 and not s.get('seeksettling'),20)
q.mark();q.keys('InstantReplay');check('configured replay seeks fifteen seconds',lambda s:s.get('player')=='paused' and 41<=s.get('seektarget',0)<=45 and not s.get('seeksettling'),20)
q.mark();q.keys('Back','Left');check('hidden-controls arrow uses configured interval',lambda s:s.get('player')=='paused' and 25<=s.get('seektarget',0)<=31,20)
q.launch('v14-sleep-countdown');check('sleep-countdown fixture plays first episode',lambda s:s.get('player')=='playing' and s.get('episode')==11)
check('natural completion opens next-episode countdown',lambda s:s.get('nextpending'),20)
check('sleep expiry cancels pending autoplay',lambda s:s.get('page')=='title' and not s.get('nextpending') and s.get('episode')==11 and 'Sleep timer ended' in s.get('status',''),15)
time.sleep(4);q.mark();check('cancelled countdown never starts late',lambda s:s.get('page')=='title' and s.get('episode')==11)
q.launch('v14-sleep-loading');check('sleep can expire during metadata loading',lambda s:'Sleep timer ended' in s.get('status','') and s.get('page')=='title',12)
time.sleep(6);q.mark();check('late stream response cannot restart after sleep',lambda s:s.get('page')=='title' and s.get('player')!='playing')
q.launch('search:pages');check('empty-filter search fixture loaded',lambda s:s.get('searchstate')=='ready')
q.mark();q.keys('Info');s=check('search filter menu available',lambda s:s.get('page')=='search-options')
i=s['searchactions'].index('filter');q.mark();q.keys(*(['Down']*i),'Select');check('movie-only filter applied',lambda s:s.get('searchfilter')=='movies')
q.mark();q.keys('Select');check('series filter applied on movie-only page',lambda s:s.get('searchfilter')=='series')
q.mark();q.keys('Back');check('empty filtered page explains scope',lambda s:s.get('page')=='search' and s.get('visibleids')==[] and 'on this page' in s.get('empty',''))
q.mark();q.keys('Fwd');check('empty filtered page still supports next page',lambda s:s.get('searchpage')==2 and s.get('searchstate')=='ready')
(q.ROOT/'build/qa-watching-extra-results.json').write_text(json.dumps(q.results,indent=2))
print('WATCHING BOUNDARY PASS',len(q.results),flush=True)
