#!/usr/bin/env python3
"""v1.4 native feature matrix; synthetic account, isolated registry only."""
import importlib.util, pathlib, json
spec=importlib.util.spec_from_file_location('acceptance',pathlib.Path(__file__).with_name('qa-acceptance.py'))
q=importlib.util.module_from_spec(spec);spec.loader.exec_module(q)
def latest(): return q.states()[-1]
def choose(field,value,focus='listfocus'):
    s=latest(); index=s[field].index(value); current=s.get(focus,0)
    q.mark(); q.keys(*(['Down']*(index-current) if index>=current else ['Up']*(current-index)), 'Select')
def select_index(index,focus='listfocus'):
    current=latest().get(focus,0)
    q.mark();q.keys(*(['Down']*(index-current) if index>=current else ['Up']*(current-index)), 'Select')
def check(name,predicate,timeout=12):return q.expect(name,predicate,timeout)
def ledger(s,ep):return next((x for x in s.get('episodehistory',[]) if x.get('episodeid')==ep),{})
q.launch('v14-ledger');check('ledger fixture seasons',lambda s:s.get('page')=='seasons')
q.mark();q.keys('Select');check('each episode shows own progress',lambda s:s.get('page')=='episodes' and any('0:07' in x for x in s.get('items',[])))
q.mark();q.keys('Select');check('old episode opens with own resume',lambda s:s.get('episode')==11 and 'restart' in s.get('titleactions',[]))
choose('titleactions','watched','actionfocus');check('mark watched preserves newer resume',lambda s:ledger(s,11).get('completed') and s['history'][0].get('episodeid')==12 and s['history'][0]['position']==6)
q.mark();q.keys('Back');check('episode list displays watched badge',lambda s:s.get('page')=='episodes' and any('Watched' in x for x in s.get('items',[])))
q.launch('v14-ledger-reload');check('watched ledger survives relaunch',lambda s:s.get('page')=='seasons' and ledger(s,11).get('completed'))
q.mark();q.keys('Select','Select');check('watched episode offers replay not resume',lambda s:s.get('page')=='title' and 'restart' not in s.get('titleactions',[]))
choose('titleactions','watched','actionfocus');check('unwatched preserves another episode resume',lambda s:not ledger(s,11).get('completed',True) and s['history'][0]['position']==6)
choose('titleactions','play','actionfocus');check('unwatched episode starts from zero',lambda s:s.get('player')=='playing' and s.get('position',99)<5)
check('episode progress advances',lambda s:s.get('position',0)>=5)
q.mark();q.keys('Play');check('episode checkpoint saved on pause',lambda s:s.get('player')=='paused' and ledger(s,11).get('position',0)>=5)
q.mark();q.keys('Back','Back');check('episode close returns to title',lambda s:s.get('page')=='title')
q.launch('v14-ledger-reload');check('independent episode checkpoint survives relaunch',lambda s:s.get('page')=='seasons' and ledger(s,11).get('position',0)>=5 and ledger(s,12).get('position')==6)

q.launch('v14-watch');check('watchlist starts in insertion order',lambda s:s.get('visibleids')==[101,201,104])
q.mark();q.keys('Right','Right');check('third watchlist card focused',lambda s:s.get('railfocus')==[0,2]);q.mark();q.keys('Info');check('watchlist options open',lambda s:s.get('page')=='watch-options')
select_index(1);check('watchlist alphabetical sorting chosen',lambda s:s.get('watchsort')=='title')
q.mark();q.keys('Back');check('watchlist sorting preserves selected title',lambda s:s.get('visibleids')==[201,104,101] and s.get('railfocus')==[0,1])
q.mark();q.keys('Info');check('watchlist options reopen',lambda s:s.get('page')=='watch-options')
select_index(0);check('movie filter chosen',lambda s:s.get('watchfilter')=='movies')
q.mark();q.keys('Back');check('movie watchlist excludes series',lambda s:s.get('visibleids')==[104,101])
q.launch('watchlist-reload');check('watchlist view preferences survive relaunch',lambda s:s.get('watchfilter')=='movies' and s.get('watchsort')=='title' and s.get('visibleids')==[104,101])
q.mark();q.keys('Select');check('filtered watchlist detail opens',lambda s:s.get('page')=='title')
q.mark();q.keys('Back');check('filtered watchlist Back restores view',lambda s:s.get('page')=='watchlist' and s.get('visibleids')==[104,101])

q.launch('search:views');check('mixed search results available',lambda s:s.get('searchstate')=='ready' and s.get('visibleids')==[301,302,303])
q.mark();q.keys('Right','Right');check('third search card focused',lambda s:s.get('railfocus')==[0,2]);q.mark();q.keys('Info');check('search options show page-scoped filters',lambda s:s.get('page')=='search-options' and any('this page' in x for x in s.get('items',[])))
choose('searchactions','filter');check('search movies selected',lambda s:s.get('searchfilter')=='movies')
choose('searchactions','sort');check('search title sort selected',lambda s:s.get('searchsort')=='title')
q.mark();q.keys('Back');check('search filters sort and preserve identity',lambda s:s.get('page')=='search' and s.get('visibleids')==[303,301] and s.get('railfocus')==[0,0])
q.mark();q.keys('Fwd');check('filtered search next provider page',lambda s:s.get('searchpage')==2 and s.get('visibleids')==[303,301])
q.mark();q.keys('Rev');check('filtered cached page returns correctly',lambda s:s.get('searchpage')==1 and s.get('visibleids')==[303,301])
q.mark();q.keys('Info');check('search options before series filter',lambda s:s.get('page')=='search-options')
choose('searchactions','filter');check('series search selected',lambda s:s.get('searchfilter')=='series')
q.mark();q.keys('Back');check('series search excludes movies',lambda s:s.get('visibleids')==[302])
q.mark();q.keys('Back','Back');check('cancelled edit retains filtered search',lambda s:s.get('page')=='search' and 'message' not in s and s.get('visibleids')==[302])

q.launch('v14-preferences');check('remote preferences open',lambda s:s.get('page')=='preferences')
select_index(0);check('arrow interval changes',lambda s:s.get('remotestep')==15)
select_index(1);check('FF interval changes independently',lambda s:s.get('remoteskip')==60 and s.get('remotestep')==15)
select_index(2);check('replay interval changes independently',lambda s:s.get('remotereplay')==15)
select_index(4);check('still-watching preference enabled',lambda s:s.get('stillminutes')==60)
q.launch('v14-preferences-reload');check('remote and still preferences persist',lambda s:s.get('remotestep')==15 and s.get('remoteskip')==60 and s.get('remotereplay')==15 and s.get('stillminutes')==60)

q.launch('v14-caption-reset');check('caption playback starts',lambda s:s.get('player')=='playing')
q.mark();q.keys('Down');check('subtitle picker opens',lambda s:s.get('trackkind')=='subtitles' and s.get('tracks'))
choose('tracklabels','Persian','trackindex');check('Persian captions visible',lambda s:s.get('captionvisible'))
q.mark();q.keys('Down');check('subtitle picker reopens',lambda s:s.get('tracks') and s.get('trackkind')=='subtitles')
choose('tracklabels','External subtitle appearance','trackindex');check('appearance picker opens',lambda s:s.get('trackkind')=='appearance')
select_index(0,'trackindex');check('solid caption background selected',lambda s:s.get('captioncontrast')=='solid')
select_index(1,'trackindex');check('raised captions selected',lambda s:s.get('captionposition')=='raised')
q.mark();q.keys('Back');check('captions clear visible controls',lambda s:s.get('captionvisible') and not s.get('tracks') and s.get('captiontranslation',[0,999])[1]+s.get('captionheight',0)+8<=416)
q.command('scripts/device.py','screenshot','build/v14-caption-appearance.jpg')
q.launch('stream:104');check('caption appearance survives relaunch',lambda s:s.get('captionposition')=='raised' and s.get('captioncontrast')=='solid' and s.get('captionvisible'))

q.launch('v14-sleep');check('sleep fixture starts playing',lambda s:s.get('player')=='playing')
check('sleep expiry saves and exits without autoplay',lambda s:s.get('page')=='title' and 'Sleep timer ended' in s.get('status','') and any(x['position']>=5 for x in s.get('history',[])),20)
q.launch('v14-still');check('still-watching fixture plays',lambda s:s.get('player')=='playing')
check('still-watching pauses with checkpoint',lambda s:s.get('watchprompt') and s.get('player')=='paused' and any(x['position']>=5 for x in s.get('history',[])),20)
q.command('scripts/device.py','screenshot','build/v14-still-watching.jpg')
q.mark();q.keys('Select');check('confirm still-watching resumes',lambda s:not s.get('watchprompt') and s.get('player')=='playing')
q.launch('v14-still');check('second still-watching prompt',lambda s:s.get('watchprompt') and s.get('player')=='paused',25)
q.mark();q.keys('Back');check('Back stops at still-watching prompt',lambda s:s.get('page')=='title' and not s.get('watchprompt'))
(q.ROOT/'build/qa-watching-results.json').write_text(json.dumps(q.results,indent=2))
print('WATCHING ACCEPTANCE PASS',len(q.results),flush=True)
